
appdynamics-otel-collector:
  clientId: <clientId>
  clientSecret: <clientSecret>
  endpoint: <endpoint>
  tokenUrl: <tokenUrl>

appdynamics-cloud-k8s-monitoring:
  install:
    logCollector: true
  clustermonConfig:
    clusterName: <clusterName>
    events:
      enabled: true
      severityToExclude: []
      reasonToExclude: []
      severeGroupByReason: []
  logCollectorConfig:
    container:
      conditions:
        - condition:
            operator: contains
            key: kubernetes.pod.name
            value: adservice
          messageParser:
            log4J:
              enabled: true
              pattern: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} %n"
          multiLinePattern: '^2022' # default is after
          multiLineNegate: true # default is false
      clusterName: <clusterName>
      dropFields: ["agent", "stream", "ecs", "input", "orchestrator", "k8s.annotations.appdynamics", "k8s.labels", "k8s.node.labels", "cloud"]
      batchSize: 1000
      loggingLevel: info
      loggingSelectors: [ "otlp" ]

