appdynamics-otel-collector:
  clientId: <clientId>
  clientSecret: <clientSecret>
  endpoint: <endpoint>
  tokenUrl: <tokenUrl>
  
appdynamics-cloud-k8s-monitoring:
  clustermonConfig:
    clusterName: <clusterName>
    events:
      enabled: true
      severityToExclude: []
      reasonToExclude: []
      severeGroupByReason: []
      
