apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: docker.io/springio/petclinic:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1000    
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app: petclinic
    service: petclinic
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: petclinic
